version: '3.5'

services:
  portfolio:
    container_name: angular-portfolio
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=dev
